config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "/emails"

  root to: "home#index"
  get 'error', to: 'home#error'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @github_link = "https://github.com/smartinez87/exception_notification"
  end

  def error
    logggger # Error Here
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/error.html.haml
Error Page

app/views/home/index.html.haml
/ Navigation
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.fixed-top
  .container
    %a.navbar-brand{:href => "#"} RubyGems
    %button.navbar-toggler{"aria-controls" => "navbarResponsive", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarResponsive", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarResponsive.collapse.navbar-collapse
      %ul.navbar-nav.ml-auto
        %li.nav-item.active
          %a.nav-link{:href => "#"}
            Exception Notification
            %span.sr-only (current)
        %li.nav-item
          %a.nav-link{ href: letter_opener_web_path, target: "_blank" } Mailbox

/ Page Content
.container
  .row
    .col-lg-4.text-center
      %h1.mt-5 Demo
    .col-lg-8
      %br
      %p.lead 
        Click the button below and check the letter opener web to see the email notification.
        %br
        %a{href: @github_link}=@github_link
      %ul.list-unstyled
        %li Version: v4.3.0
        %li Last Updated: 26th Mar 2019
  .row
    .col-lg-12
      .card
        .card-block.text-center.align-middle{style: "padding:20px;min-height:200px"}   
          %br 
          =link_to "Error Page", error_path, class: "btn btn-primary"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title Exception Notification
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    :css
      body {
        padding-top: 54px;
      }
      @media (min-width: 992px) {
        body {
          padding-top: 56px;
        }
      }

    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield